### ISSUE TITLE
блять 

### ISSUE THREAD

**Issue by demndevel** [BiteDasher/vkidalog#1]
ты мне отфарматировал диск)))) лан прощаю 
короче сделай возможность инсталляции рядом с шиндой  для ретардов

**Comment by BiteDasher** [comment]
Токо что поставил на QEMU рядом с другими разделами, ничего не удалилось, смотри что делаешь, а то видимо руки из одного места

**Comment by BiteDasher** [comment]
скрипт если что рассчитан на дуал бут

**Comment by demndevel** [comment]
> 
> 
> скрипт если что рассчитан на дуал бут

ok
